1069 - Fix enabling lookup elements when initially disabled
infor-design/enterprise-ng pull request #1074
Opened 2021-07-07 08:17 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the enabling of lookup elements (lookup input field and button icon trigger) when the component is initially disabled.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-ng/issues/1069

**Steps necessary to review your pull request (required)**:
- Pull this branch

```powershell
npm run build
npm run start
```
- Go to http://localhost:4200/ids-enterprise-ng-demo/lookup
- Find the label `Toggle isDisabled`, and click `Enable`
- It should enable the input field, and the trigger button
- Click the trigger button to check if it's working
- Click `Disable`, and it should disable the component

2021-07-07 15:41 UTC, tmcconechy commented
@anhallbe can you test this fix on your end please?

2021-07-07 15:41 UTC, tmcconechy approved these changes

2021-07-08 09:30 UTC, anhallbe commented
Yep! I'll test it ASAP

2021-07-08 11:17 UTC, anhallbe commented
I cherry-picked these changed on to the `9.5.0` tag and tested.

The issue is solved, but I noticed that the disabled state can no longer be controlled with `[attr.disabled]="shouldBeDisabled ? '' : null"`, which is a pretty common pattern that will no longer work.

2021-07-08 11:23 UTC, ericangeles commented
@anhallbe any suggestions you think that fits on your end?

2021-07-08 12:19 UTC, anhallbe commented
@ericangeles How about this?
```typescript
// 1. Changed type of ElementRef for better typings:
constructor(private element: ElementRef<HTMLInputElement>, private ngZone: NgZone) {
    super();
}

// 2, Added check for attribute in ngAfterViewChecked:
// enabling all elements of lookup when component is initially disabled
if (!this.isDisabled && !this.element.nativeElement.getAttribute("disabled")) {
    this.enable();
}
```

I have tested with the following and it seems to work:
- `[isDisabled]="isDisabled"`
- `[isDisabled]="!isDisabled"`
- `[disabled]="isDisabled"`
- `[disabled]="!isDisabled"`
- `[attr.disabled]="isDisabled ? '' : null"`
- `[attr.disabled]="isDisabled ? null : ''"`

2021-07-08 12:29 UTC, ericangeles commented
@anhallbe, all set! Thanks!

2021-07-08 12:30 UTC, anhallbe commented
Awesome! I'll just do a final deploy/test in HP to confirm it works

2021-07-08 13:23 UTC, tmcconechy approved these changes

2021-07-08 14:02 UTC, tmcconechy commented
@anhallbe just let us know and i'll merge this and patch.

2021-07-08 15:05 UTC, deep7102 approved these changes
🍌

2021-07-09 09:11 UTC, anhallbe commented
My fix didn't work, apparently... :(

I think some unit tests for the "disabled" state would be nice to have, since there are at least 5 different ways to control the disabled state, and each change seems to break at least one of them.

2021-07-09 12:59 UTC, tmcconechy requested changes
Not that up on this fix but sounds like we need to keep looking?

2021-07-09 15:02 UTC, tmcconechy commented
@anhallbe what do you think of my fix - i saw the timepicker works with `[attr.disabled]` instead as do many others. So i changed this so that that works. I kept the older isDisabled in though for compatibility.

```
       <div class="field">
          <label soho-label for="toggle-disabled">Toggle isDisabled</label>
          <label soho-label for="readonly">Readonly [attr.readonly]</label>
          <input soho-lookup
            [isDisabled]="isDisabled"
            [attr.readonly]="isDisabled"
            [(ngModel)]="model.single"
            [columns]="columns_product"
            [dataset]="data_product"
            field="productId"
            title="Products"
            name="readonly" />
        </div>
        <div class="field">
          <label soho-label for="toggle-disabled">Toggle [attr.disabled]</label>
          <input soho-lookup
            [attr.disabled]="isDisabled ? '' : null"
            [(ngModel)]="model.single"
            [columns]="columns_product"
            [dataset]="data_product"
            field="productId"
            title="Products"
            name="toggle-disabled" />
        </div>
```

What do you think of this approach?

2021-07-11 22:54 UTC, bthharper commented
I am not sure if this 100% fixes the issue, but please review the changes in the branch "1069-lookup-init-diable-v2".

2021-07-11 23:26 UTC, bthharper requested changes
This is normally done using a `HostBinding` on the component.  

I do see an issue with the original code, where the `HostBinding` was incorrect.  It should be :

```typescript
@HostBinding('disabled')
@Input() isDisabled: boolean | undefined = undefined;
```

Avoid casting to `any`, you can use the elvis operator (?) to ensure type safety, e.g.:

```typescript
this.lookup?.disable();
```

Need to check with @tmcconechy, but does the disable / enable method actually do anything on the widget other than add disabled?

2021-07-12 04:49 UTC, ericangeles commented
Looking at @bthharper implementation, it does fixed the issue.

2021-07-12 04:49 UTC, ericangeles commented
Looking at @bthharper implementation, it does fix the issue.

2021-07-12 09:58 UTC, anhallbe commented
I tried to set up a test for this, since there are so many ways of disabling a Lookup. I didn't quite get there just yet since the "initially disabled" part is a bit tricky to test. This is what I came up with so far:

```typescript
@Component({
  template: `
    <input #disabledBound soho-lookup [disabled]="disabled">

    <input #isDisabledBound soho-lookup [isDisabled]="disabled">

    <input #attrDisabledBound soho-lookup [attr.disabled]="disabled ? '' : null">

    <input #reactiveFormBound [formControl]="reactiveControl" soho-lookup>

    <input #controlledByMethod soho-lookup>

    <input #controlledBySetDisabledState soho-lookup>
  `,
})
class DisabledTestComponent {
  @ViewChild("disabledBound", { read: ElementRef }) disabledBound!: ElementRef<HTMLInputElement>;
  @ViewChild("isDisabledBound", { read: ElementRef }) isDisabledBound!: ElementRef<HTMLInputElement>;
  @ViewChild("attrDisabledBound", { read: ElementRef }) attrDisabledBound!: ElementRef<HTMLInputElement>;
  @ViewChild("reactiveFormBound", { read: ElementRef }) reactiveFormBound!: ElementRef<HTMLInputElement>;
  @ViewChild("controlledByMethod", { read: ElementRef }) controlledByMethod!: ElementRef<HTMLInputElement>;
  @ViewChild("controlledByMethod", { read: SohoLookupComponent }) private controlledByMethodCmp!: SohoLookupComponent;
  @ViewChild("controlledBySetDisabledState", { read: ElementRef }) controlledBySetDisabledState!: ElementRef<HTMLInputElement>;
  @ViewChild("controlledBySetDisabledState", { read: SohoLookupComponent }) private controlledBySetDisabledStateCmp!: SohoLookupComponent;


  reactiveControl = this.formBuilder.control("");
  disabled?: boolean;

  constructor(private formBuilder: FormBuilder) { }

  disableAll() {
    this.disabled = true;
    this.reactiveControl.disable();
    this.controlledByMethodCmp.disable();
    this.controlledBySetDisabledStateCmp.setDisabledState(true);
  }

  enableAll() {
    this.disabled = false;
    this.reactiveControl.enable();
    this.controlledByMethodCmp.disable();
    this.controlledBySetDisabledStateCmp.setDisabledState(false);
  }
}

describe('SohoLookupComponent disabled state', () => {

  let fixture: ComponentFixture<DisabledTestComponent>;
  let component: DisabledTestComponent;

  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [DisabledTestComponent],
      imports: [
        SohoLookupModule,
        ReactiveFormsModule,
      ],
    });

    fixture = TestBed.createComponent(DisabledTestComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  describe("when initially disabled", () => {
    beforeEach(async () => {
      await disableAll();
    });

    it("should be disabled when [isDisabled] is true", async () => {
      await disableAll();
      expectDisabled(component.isDisabledBound)
    });

    it("should be enabled when [isDisabled] is false", async () => {
      await enableAll();
      expectEnabled(component.isDisabledBound)
    });

    it("should be disabled when [disabled] is true", async () => {
      await disableAll();
      expectDisabled(component.disabledBound)
    });

    it("should be enabled when [disabled] is false", async () => {
      await enableAll();
      expectEnabled(component.disabledBound)
    });

    it("should be disabled when [attr.disabled] is ''", async () => {
      await disableAll();
      expectDisabled(component.attrDisabledBound)
    });

    it("should be enabled when [attr.disabled] is null", async () => {
      await enableAll();
      expectEnabled(component.attrDisabledBound)
    });

    it("should be disabled when [formControl] is disabled", async () => {
      await disableAll();
      expectDisabled(component.reactiveFormBound)
    });

    it("should be enabled when [formControl] is enabled", async () => {
      await enableAll();
      expectEnabled(component.reactiveFormBound)
    });

    it("should be disabled when #disable() has been called", async () => {
      await disableAll();
      expectDisabled(component.controlledByMethod)
    });

    it("should be enabled when #enable() has been called", async () => {
      await enableAll();
      expectEnabled(component.controlledByMethod)
    });

    it("should be disabled when #setDisabledState(true) has been called", async () => {
      await disableAll();
      expectDisabled(component.controlledBySetDisabledState)
    });

    it("should be enabled when #setDisabledState(false) has been called", async () => {
      await enableAll();
      expectEnabled(component.controlledBySetDisabledState)
    });
  })

  describe("when initially enabled", () => {
    beforeEach(async () => {
      await enableAll();
    });

    it("should be disabled when [isDisabled] is true", async () => {
      await disableAll();
      expectDisabled(component.isDisabledBound)
    });

    it("should be enabled when [isDisabled] is false", async () => {
      await enableAll();
      expectEnabled(component.isDisabledBound)
    });

    it("should be disabled when [disabled] is true", async () => {
      await disableAll();
      expectDisabled(component.disabledBound)
    });

    it("should be enabled when [disabled] is false", async () => {
      await enableAll();
      expectEnabled(component.disabledBound)
    });

    it("should be disabled when [attr.disabled] is ''", async () => {
      await disableAll();
      expectDisabled(component.attrDisabledBound)
    });

    it("should be enabled when [attr.disabled] is null", async () => {
      await enableAll();
      expectEnabled(component.attrDisabledBound)
    });

    it("should be disabled when [formControl] is disabled", async () => {
      await disableAll();
      expectDisabled(component.reactiveFormBound)
    });

    it("should be enabled when [formControl] is enabled", async () => {
      await enableAll();
      expectEnabled(component.reactiveFormBound)
    });

    it("should be disabled when #disable() has been called", async () => {
      await disableAll();
      expectDisabled(component.controlledByMethod)
    });

    it("should be enabled when #enable() has been called", async () => {
      await enableAll();
      expectEnabled(component.controlledByMethod)
    });

    it("should be disabled when #setDisabledState(true) has been called", async () => {
      await disableAll();
      expectDisabled(component.controlledBySetDisabledState)
    });

    it("should be enabled when #setDisabledState(false) has been called", async () => {
      await enableAll();
      expectEnabled(component.controlledBySetDisabledState)
    });
  });

  async function disableAll() {
    await setAllDisabled(true);
  }

  async function enableAll() {
    await setAllDisabled(false);
  }

  async function setAllDisabled(disabled: boolean) {
    if (disabled) {
      component.disableAll();
    } else {
      component.enableAll();
    }
    fixture.detectChanges();
    await fixture.whenStable();
  }

  function expectDisabled(element: ElementRef<HTMLInputElement>) {
    expect(element.nativeElement.disabled).toBeTrue();
  }

  function expectEnabled(element: ElementRef<HTMLInputElement>) {
    expect(element.nativeElement.disabled).toBeFalse();
  }
});

```

2021-07-12 12:58 UTC, tmcconechy commented
Closing this in favor of https://github.com/infor-design/enterprise-ng/pull/1076

2021-07-12 12:58 UTC, closed without merging