1169 - Notification Badge Features
infor-design/enterprise-ng pull request #1187
Opened 2021-11-26 11:02 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR is a follow up fix for Caps Tabs Vertical Scroll.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1169

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/contextualactionpanel/example-cap-tabs-vertical-scroll.html
- Scroll the sidebar

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-11-29 16:09 UTC, tmcconechy requested changes
1. should we use notificationBadge instead of badge for the setting?
2. instead of enable/disable. I think hide/show is better (i see what your doing now)

2021-11-29 16:09 UTC, tmcconechy commented on projects/ids-enterprise-ng/src/lib/accordion/soho-accordion.component.ts
> +  @Input() public set badge(badge: boolean | undefined) {
Maybe should be notificationBadge instead of badge?

2021-11-29 16:09 UTC, tmcconechy commented on projects/ids-enterprise-typings/lib/notification-badge/soho-notification-badge.d.ts
> +  enable(): void;
Can you really enable and disable badges?

2021-12-02 13:20 UTC, tmcconechy commented
Issues seems to be waiting on https://github.com/infor-design/enterprise/pull/5914 to continue

2021-12-02 14:26 UTC, tjamesallen15 commented
> Issues seems to be waiting on [infor-design/enterprise#5914](https://github.com/infor-design/enterprise/pull/5914) to continue

Also this one. https://github.com/infor-design/enterprise/pull/5910

2021-12-07 14:48 UTC, tmcconechy commented
@tjamesallen15 this is ready now? If so seems to be a couple merge conflicts.

2021-12-09 01:49 UTC, tjamesallen15 commented
> @tjamesallen15 this is ready now? If so seems to be a couple merge conflicts.

Sorry for the delay. I just fix the merge conflicts now.

2021-12-09 19:42 UTC, tmcconechy submitted a review, later dismissed

2021-12-10 14:25 UTC, merged