1378 - datagrid unnecessary role on parent
infor-design/enterprise-ng pull request #1391
Opened 2022-10-18 01:14 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will remove unnecessary role on datagrid.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1378

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-10-18 07:17 UTC, ericangeles commented
@tjamesallen15 please fix the conflict and we are now on `14.5.0`.

2022-10-18 13:43 UTC, tmcconechy requested changes
@tjamesallen15 it could be a problem that the package-lock.json is effected. Can you copy the current one over so this isnt changed? This could be your on node 14 when this repo uses node 16.

Rest looks good

2022-10-19 15:13 UTC, tmcconechy approved these changes

2022-10-19 15:13 UTC, tmcconechy approved these changes

2022-10-21 13:43 UTC, tmcconechy approved these changes

2022-10-25 02:24 UTC, ericangeles approved these changes

2022-10-25 02:24 UTC, merged

2022-10-31 19:30 UTC, CindyMercadoReyes commented
This issue is now resolved.