Update soho-monthview.component.ts, exposed showMonth() method
infor-design/enterprise-ng pull request #1503
Opened 2023-06-13 15:29 UTC by yousef-elkaisi

Added public showMonth() method to allow the month to be manually set.

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This allows us to manually set the month and year of the monthview component.

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:
Create a monthview component and call the showMonth() method through the viewchild accessor. Confirm that the month is changed to the value that was set.

2023-06-13 16:14 UTC, tmcconechy approved these changes

2023-06-13 18:50 UTC, tmcconechy requested changes
@yousef-elkaisi Seems to not compile https://github.com/infor-design/enterprise-ng/actions/runs/5257447799/jobs/9501402032?pr=1503#step:5:32

2023-06-14 15:21 UTC, ericangeles commented
@yousef-elkaisi, you might want to consider using optional chaining. For example, you could use `this.monthview?.showMonth(month, year);`.

2023-06-14 15:40 UTC, yousef-elkaisi commented
@tmcconechy @ericangeles I added a null check and casted monthview as 'any'. This should fix the compile issues.

2023-06-14 17:28 UTC, merged